#ACTIVIDAD 1

Consigna:

Filtrar pasajeros sobrevivientes: Tu primer paso será identificar y extraer a los pasajeros que lograron sobrevivir al desastre.

Seleccionar columnas relevantes: De los sobrevivientes, deberás extraer únicamente las columnas que te interesan para el análisis: 'sex', 'age' y 'fare'.

Crear una nueva columna: Vas a agregar una nueva columna al DataFrame que clasifique a cada pasajero según la clase en la que viajaban, etiquetándola como una categoría.

In [ ]:
import pandas as pd
import seaborn as sns

df_titanic = sns.load_dataset('titanic')
df_titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [ ]:
df_titanic_alive = df_titanic.query("alive == 'yes'")
df_titanic_noAlive = df_titanic.query("alive == 'no'")
print("pasajeros sobrevivientes: ", df_titanic_alive.shape[0])
print("pasajeros no sobrevivientes: ", df_titanic_noAlive.shape[0])

pasajeros sobrevivientes:  342
pasajeros no sobrevivientes:  549

In [ ]:
df_titanic_alive.columns
df_filtrado = df_titanic_alive[['sex', 'age', 'fare']]
df_filtrado

        sex   age     fare
1    female  38.0  71.2833
2    female  26.0   7.9250
3    female  35.0  53.1000
8    female  27.0  11.1333
9    female  14.0  30.0708
..      ...   ...      ...
875  female  15.0   7.2250
879  female  56.0  83.1583
880  female  25.0  26.0000
887  female  19.0  30.0000
889    male  26.0  30.0000

[342 rows x 3 columns]

In [ ]:
df_filtrado['categoria'] = df_titanic["class"].map({
    "First" : "A",
    "Second" : "B",
    "Third" : "C"
})
df_filtrado

/tmp/ipython-input-3840016339.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtrado['categoria'] = df_titanic["class"].map({

        sex   age     fare categoria
1    female  38.0  71.2833         A
2    female  26.0   7.9250         C
3    female  35.0  53.1000         A
8    female  27.0  11.1333         C
9    female  14.0  30.0708         B
..      ...   ...      ...       ...
875  female  15.0   7.2250         C
879  female  56.0  83.1583         A
880  female  25.0  26.0000         B
887  female  19.0  30.0000         A
889    male  26.0  30.0000         A

[342 rows x 4 columns]

#ACTIVIDAD 2

Consigna:

Practicar la manipulación de datos haciendo selecciones y transformaciones sobre el conjunto de datos de Titanic:

Obtener los nombres de las columnas del DataFrame.

Eliminar la columna 'deck'. (tener en cuenta que puede contener valores nulos y la función puede dar advertencias).

Reindexar el DataFrame después de eliminar la columna.

In [14]:
import seaborn as sns1

df_new_titanic = sns1.load_dataset('titanic')

#-------------- COLUMNAS --------------
df_new_titanic.columns

df_new_titanic = df_new_titanic.drop(columns=['deck'])
df_new_titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,Queenstown,no,True

In [21]:
# ---------------- REINDEXACIÓN ------------------

df_new_titanic.reset_index(drop=True, inplace=True)
df_new_titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,Queenstown,no,True